proljece:
    datasource:
        password: password
        pozdrav1: veliki_pozdrav2
        pozdrav2: mali_pozdrav2
        url: jdbc:h2:dev
        username: SA
hum.name: humidity-ms2
temp.name: temperature-ms2
agg.name: aggregator-ms2