proljece:
    datasource:
        password: password
        pozdrav1: veliki_pozdrav2
        pozdrav2: mali_pozdrav2
        url: jdbc:h2:dev
        username: SA
data:
    temperature-unit: K
    temperature-microservice: temperature-ms3
    humidity-microservice: humidity-ms3
    aggregator-microservice: aggregator-ms3