services:
  config:
    image: config-server-jib
    ports:
      - "8888:8888"
  eureka:
    image: eureka-server-jib
    ports:
      - "8761:8761"
    depends_on:
      - "config"
    command: ["./wait-for-it.sh", "config:8888"]
  humidity:
    image: humidity-jib
    ports:
      - "8082:8082"
    depends_on:
      - "eureka"
    command: ["./wait-for-it.sh", "eureka:8761"]
  temperature:
    image: temperature-jib
    ports:
      - "8083:8083"
    depends_on:
      - "humidity"
    command: ["./wait-for-it.sh", "humidity:8082"]
  aggregator:
    image: aggregator-jib
    ports:
      - "8081:8081"
    depends_on:
      - "temperature"
    command: [ "./wait-for-it.sh", "temperature:8083"]