spring.h2.console.enabled: true
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
server.port: 8081
spring.application.name: ${data.aggregator-microservice}
configpath: config
management.endpoints.web.exposure.include: "*"
spring.cloud.config.enabled: true
spring.config.discovery.enabled: true
spring.config.discovery.service-id: configServer
spring.config.import: configserver:http://config:8888
data:
  temperature-unit: C
  temperature-microservice: temperature-ms
  humidity-microservice: humidity-ms
  aggregator-microservice: aggregator-ms
