spring.h2.console.enabled: true
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
server.port: 8081
spring.application.name: aggregator-ms
spring.cloud.config.uri: http://localhost:8888

configpath: config
management.endpoints.web.exposure.include: "*"
spring.cloud.config.enabled: true

spring:
  cloud:
    config:
      fail-fast: true
  datasource:
    password: password
    pozdrav1: krivi
    pozdrav2: krivi