spring.h2.console.enabled: true
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
server.port: 8081
spring.application.name: aggregator-ms
configpath: config
management.endpoints.web.exposure.include: "*"
spring.cloud.config.enabled: true
spring.config.import: configserver:http://localhost:8888
spring:
  datasource:
    password: password
    pozdrav1: krivi
    pozdrav2: krivi
